### ISSUE TITLE
ImageBitmap is only supported in WebGL2

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-context#120]
As per https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D

Should we warn in pex-context or rely on browser to fail? Is creates issue here https://github.com/pex-gl/pex-renderer/blob/v4/loaders/glTF.js#L1234

**Comment by dmnsgn** [comment]
I'd say yes, warning in pex-context but also overwrite supportImageBitmap by checking isWebGL2 in pex-renderer.

**Comment by vorg** [comment]
Btw FF gives better error in WebGL1 `WebGLRenderingContext.texImage2D: Argument 9 does not implement interface ArrayBufferViewOrNull.`

**Comment by vorg** [comment]
Possible fix here https://stackoverflow.com/questions/42073596/webglrenderingcontext-teximage2d-does-not-implement-interface-arraybuffervieworn

**Comment by dmnsgn** [comment]
Proposed change: check if ImageBitmap in webgl.

```diff
   }
 
   const img = opts.data ? opts.data : opts;
-  if (img && img.nodeName) {
+  if (
+    (img && img.nodeName) ||
+    (!ctx.capabilities.isWebGL2 && img instanceof ImageBitmap)
+  ) {
   
```

**Comment by vorg** [comment]
Looks good to me
