### ISSUE TITLE
Include WebGL2 feature in ctx.capabilities

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-context#129]
Currently e.g. ctx.capabilities.textureHalfFloat is false for WebGL2 context.

**Comment by dmnsgn** [comment]
The question is: are capabalities detecting "extension presence" or WebGL (1 or 2) "functionality".

**Comment by dmnsgn** [comment]
Note: textureFloatLinear, textureHalfFloatLinear and textureFilterAnisotropic are still extensions in WebGL2 and not enabled by default.
