### ISSUE TITLE
extDTQ is null in Firefox

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-context#143]
This crashes in FF https://github.com/pex-gl/pex-context/blob/4cad08c43de9099a31b765827115a37f4acaa7b5/polyfill.js#L56-L58

Strange but https://webglreport.com/?v=2 shows [EXT_disjoint_timer_query](https://www.khronos.org/registry/webgl/extensions/EXT_disjoint_timer_query) in WebGL2 Tab while other browsers show [EXT_disjoint_timer_query_webgl2](https://www.khronos.org/registry/webgl/extensions/EXT_disjoint_timer_query_webgl2)

**Comment by dmnsgn** [comment]
What do you mean crash?
FF [doesn't have support for it ](https://developer.mozilla.org/en-US/docs/Web/API/EXT_disjoint_timer_query#browser_compatibility) in theory.

My FF 127 is not showing neither EXT_disjoint_timer_query nor EXT_disjoint_timer_query_webgl2.

**Comment by vorg** [comment]
Dead node on graph load

![Screenshot 2024-07-05 at 11 35 12](https://github.com/pex-gl/pex-context/assets/171001/5ee2897c-8c99-4648-a145-b2cd64bc9331)

**Comment by dmnsgn** [comment]
And to confirm, console logs a `webgl2` context, right?

**Comment by vorg** [comment]
yes webgl2

![Screenshot 2024-07-05 at 14 24 44](https://github.com/pex-gl/pex-context/assets/171001/bcce2f15-028d-4203-8d92-e7e57517c9ac)

![Screenshot 2024-07-05 at 14 24 46](https://github.com/pex-gl/pex-context/assets/171001/7245fe14-ec1d-4bc1-9819-93c50cfebee5)

**Comment by vorg** [comment]
> My FF 127 is not showing neither EXT_disjoint_timer_query nor EXT_disjoint_timer_query_webgl2.

How come i have it here https://webglreport.com/?v=2

![Screenshot 2024-07-05 at 14 28 35](https://github.com/pex-gl/pex-context/assets/171001/93cbea33-2d6e-4430-baa8-d730555df2ff)
