### ISSUE TITLE
Remove ramda

### ISSUE THREAD

**Issue by nicknikolov** [pex-gl/pex-context#24]
To see if it helps with size

**Comment by vorg** [comment]
We can actually provide our own implementation of flatten and get rid of Ramda completely. What always flatten 2 levels deep arrays so we could also preallocate them with `len = a.length * a[0].length`

**Comment by vorg** [comment]
Fixed in https://github.com/pex-gl/pex-context/commit/748f7baebf443bb567f282998e2e263eb9415182

**Comment by vorg** [comment]
Didn't help with size as I was using only `require('ramda/src/flatten')`
