### ISSUE TITLE
webgpu support

### ISSUE THREAD

**Issue by Francois-Esquire** [pex-gl/pex-context#82]
Hi there!

Is there any future plan to support [`webgpu`](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status)?

**Comment by vorg** [comment]
As for my tweet some time ago https://twitter.com/marcinignac/status/1127935531848019970 there are indeed lots of similarities but also many differences... I have a rough version working here https://github.com/vorg/pex-20001-webgpu that introduces new concepts like samplers, bindings and UBOs but for real work to happen Safari has to enable WebGL2 so I can figure out what would be best common interface.

![attractor-lines-04 2020-02-19 14-29-54](https://user-images.githubusercontent.com/171001/74881311-fc1fd100-5364-11ea-92d7-bfd9431985fe.png)

**Comment by Francois-Esquire** [comment]
Awesome news! I felt pex was a natural candidate for webgpu when I learned more about the proposal, really glad to read and see a prototype 👏

Closing issue, question answered, thank you @vorg !
